### PR TITLE
:sparkles: add OOP Record in UI and Fix Class record to other class

### LINKED ISSUE #23: Change UI System to button to change btw Graph and Video camera
Task 
- After the Record will change to the Result UI 
- Btn Record Video and save 
- Create button change to Graph
- Create button change to Video

### PR DESCRIPTION
**Pull request by Pet002**
i use class records to inherit Processes from multiprocessing to a new class for UI to get this class to using

### CODE REVIEW

**Comment by Pet002** [comment]
can you review this @HanawuZ 
and can u fix it ? 😆

**Comment by Pet002** [comment]
I need to know, why image in Tkinkter is slow than pure cv2? and can optimize this in Tkinter?

**Comment by HanawuZ** [comment]
> I need to know, why image in Tkinkter is slow than pure cv2? and can optimize this in Tkinter?

Because we resize frame every frame. This make Tkinter slow

**Comment by Pet002** [comment]
Thanks 😄  
and i get a new bug when I record 
image
what is ??

**Comment by Pet002** [comment]
i will fix it in a minute.

**Comment by Pet002** [comment]
I think i found it 

in Tkinter Is cannot pass parameter cv2 to object so it will error.

i will fix it in tomorrow.

**Comment by Pet002** [comment]
Nice debug can i merge it?

**Review by HanawuZ — APPROVED** [review]

**Pull request merged**
